name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # ou qualquer outra branch que você estiver usando

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Fly CLI
      run: |
        curl -L https://fly.io/install.sh | sh
        export FLYCTL_INSTALL="/home/runner/.fly"
        export PATH="$FLYCTL_INSTALL/bin:$PATH"

    - name: Deploy to Fly.io
      run: flyctl deploy --token ${{ secrets.FLY_API_TOKEN }}
