name: Deploy no Fly.io

on:
  push:
    branches:
      - main  # ou a branch que você quer usar para deploy automático

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Fly CLI
        run: curl -L https://fly.io/install.sh | sh

      - name: Autenticar no Fly.io
        run: |
          export FLYCTL_INSTALL="/home/runner/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          flyctl auth token ${{ secrets.FLY_API_TOKEN }}

      - name: Fazer deploy
        run: |
          export FLYCTL_INSTALL="/home/runner/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          flyctl deploy
